---
codecov:
  notify:
    after_n_builds: 1
coverage:
  status:
    patch:
      default:
        target: 80%
        paths:
        - src/
        - frontend/src/
    project:
      default: false  # disable default status
      backend:
        target: 80%
        paths:
        - src/
      frontend:
        target: 80%
        paths:
        - frontend/src/
      tests:  # report coverage status for tests...
        target: 0%  # ... but let the check always pass
        paths:
        - tests/

# makes no sense to execute benchmarks with coverage instrumentation
ignore:
- benchmarks
