sonar.projectKey=renefritze_corvix
sonar.projectName=corvix

sonar.sources=src,frontend/src
sonar.tests=tests,frontend/src
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**/*,tests/**/*
sonar.exclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx

sonar.sourceEncoding=UTF-8
