sonar.projectKey=renefritze_corvix
sonar.projectName=corvix

sonar.sources=src,frontend/src
sonar.tests=tests,frontend/src/test
sonar.test.inclusions=tests/**/*.py,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/test/**/*

sonar.sourceEncoding=UTF-8
