/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["Index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DashboardsDeprecated */
        get: operations["ApiDashboardsDashboardsDeprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** HealthDeprecated */
        get: operations["ApiHealthHealthDeprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{account_id}/{thread_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DismissNotificationDeprecated */
        post: operations["ApiNotificationsAccountIdThreadIdDismissDismissNotificationDeprecated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{account_id}/{thread_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MarkNotificationReadDeprecated */
        post: operations["ApiNotificationsAccountIdThreadIdMarkReadMarkNotificationReadDeprecated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{account_id}/{thread_id}/rule-snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NotificationRuleSnippetsDeprecated */
        get: operations["ApiNotificationsAccountIdThreadIdRuleSnippetsNotificationRuleSnippetsDeprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{thread_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DismissNotificationDefaultAccount */
        post: operations["ApiNotificationsThreadIdDismissDismissNotificationDefaultAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{thread_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MarkNotificationReadDefaultAccount */
        post: operations["ApiNotificationsThreadIdMarkReadMarkNotificationReadDefaultAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SnapshotDeprecated */
        get: operations["ApiSnapshotSnapshotDeprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ApiThemesDeprecated */
        get: operations["ApiThemesApiThemesDeprecated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboards */
        get: operations["ApiV1DashboardsDashboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["ApiV1EventsEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["ApiV1HealthHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{account_id}/{thread_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DismissNotification */
        post: operations["ApiV1NotificationsAccountIdThreadIdDismissDismissNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{account_id}/{thread_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MarkNotificationRead */
        post: operations["ApiV1NotificationsAccountIdThreadIdMarkReadMarkNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{account_id}/{thread_id}/rule-snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NotificationRuleSnippets */
        get: operations["ApiV1NotificationsAccountIdThreadIdRuleSnippetsNotificationRuleSnippets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["ApiV1SnapshotSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ApiThemes */
        get: operations["ApiV1ThemesApiThemes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboards/{dashboard_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DashboardIndex */
        get: operations["DashboardsDashboardNameDashboardIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LoginPage */
        get: operations["LoginLoginPage"];
        put?: never;
        /** Login */
        post: operations["LoginLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["LogoutLogout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MetricsEndpoint */
        get: operations["MetricsMetricsEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrowserTabNotificationsConfigResponse */
        BrowserTabNotificationsConfigResponse: {
            cooldown_seconds: number;
            enabled: boolean;
            max_per_cycle: number;
        };
        /** DashboardGroupResponse */
        DashboardGroupResponse: {
            items: components["schemas"]["DashboardItemResponse"][];
            name: string;
        };
        /** DashboardItemResponse */
        DashboardItemResponse: {
            account_id: string;
            account_label: string;
            actions_taken: string[];
            matched_rules: string[];
            reason: string;
            repository: string;
            score: number;
            subject_title: string;
            subject_type: string;
            thread_id: string;
            unread: boolean;
            updated_at: string;
            web_url: string | null;
        };
        /** DashboardSummaryResponse */
        DashboardSummaryResponse: {
            group_count: number;
            read_items: number;
            reason_count: number;
            repository_count: number;
            unread_items: number;
        };
        /** NotificationsConfigResponse */
        NotificationsConfigResponse: {
            browser_tab: components["schemas"]["BrowserTabNotificationsConfigResponse"];
            enabled: boolean;
        };
        /** PollerStatusResponse */
        PollerStatusResponse: {
            last_error: string | null;
            last_error_time: string | null;
            last_poll_time: string | null;
            stale: boolean;
            status: string;
        };
        /** RuleSnippetsResponse */
        RuleSnippetsResponse: {
            dashboard_ignore_rule_snippet: string;
            dashboard_ignore_rule_with_context_snippet: string | null;
            dashboard_name: string;
            global_exclude_rule_snippet: string;
            global_exclude_rule_with_context_snippet: string | null;
            has_context: boolean;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            dashboard_names: string[];
            descending: boolean;
            generated_at: string | null;
            groups: components["schemas"]["DashboardGroupResponse"][];
            include_read: boolean;
            name: string;
            notifications_config: components["schemas"]["NotificationsConfigResponse"] | null;
            poller: components["schemas"]["PollerStatusResponse"];
            sort_by: string;
            summary: components["schemas"]["DashboardSummaryResponse"];
            total_items: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    ApiDashboardsDashboardsDeprecated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ApiHealthHealthDeprecated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ApiNotificationsAccountIdThreadIdDismissDismissNotificationDeprecated: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiNotificationsAccountIdThreadIdMarkReadMarkNotificationReadDeprecated: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiNotificationsAccountIdThreadIdRuleSnippetsNotificationRuleSnippetsDeprecated: {
        parameters: {
            query?: {
                dashboard?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSnippetsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiNotificationsThreadIdDismissDismissNotificationDefaultAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiNotificationsThreadIdMarkReadMarkNotificationReadDefaultAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiSnapshotSnapshotDeprecated: {
        parameters: {
            query?: {
                dashboard?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiThemesApiThemesDeprecated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ApiV1DashboardsDashboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ApiV1EventsEvents: {
        parameters: {
            query?: {
                dashboard?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1HealthHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ApiV1NotificationsAccountIdThreadIdDismissDismissNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1NotificationsAccountIdThreadIdMarkReadMarkNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1NotificationsAccountIdThreadIdRuleSnippetsNotificationRuleSnippets: {
        parameters: {
            query?: {
                dashboard?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSnippetsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1SnapshotSnapshot: {
        parameters: {
            query?: {
                dashboard?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1ThemesApiThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    DashboardsDashboardNameDashboardIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dashboard_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    LoginLoginPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    LoginLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
        };
    };
    LogoutLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
        };
    };
    MetricsMetricsEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
