"""Contract tests binding the backend API to its generated schema.

These guard the schema contract described in issue F7:

* the committed OpenAPI document (``frontend/openapi.json``) stays in sync with
  the Litestar app's auto-generated schema, so a backend field change that is
  not regenerated fails CI rather than silently breaking the frontend;
* the actual JSON the handlers emit conforms to the typed response schemas in
  ``corvix.web.schemas`` (every declared field present, correctly typed, and no
  undeclared extras).

The TypeScript side of the contract (``frontend/src/api-types.gen.ts``) is
drift-checked in CI via ``make gen-types`` + ``git diff --exit-code``.
"""

from __future__ import annotations

import dataclasses
import importlib.util
import json
from collections.abc import Generator
from pathlib import Path
from types import ModuleType

import msgspec
import pytest
from litestar.testing import TestClient

from corvix.config import load_config
from corvix.web.app import app
from corvix.web.schemas import RuleSnippetsResponse, SnapshotResponse
from corvix.web.storage_provider import set_storage_backend
from tests.support.storage import JsonFileStorage

_REPO_ROOT = Path(__file__).resolve().parents[2]
_OPENAPI_PATH = _REPO_ROOT / "frontend" / "openapi.json"
_GENERATED_TS_PATH = _REPO_ROOT / "frontend" / "src" / "api-types.gen.ts"


def _load_export_module() -> ModuleType:
    """Import ``scripts/export_openapi.py`` as a module (it is not a package)."""
    spec = importlib.util.spec_from_file_location(
        "corvix_export_openapi",
        _REPO_ROOT / "scripts" / "export_openapi.py",
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_openapi_matches_app_schema() -> None:
    """The committed OpenAPI doc must match what the app generates now."""
    export = _load_export_module()
    rendered = export.render_openapi()
    committed = json.loads(_OPENAPI_PATH.read_text(encoding="utf-8"))
    assert rendered == committed, (
        "frontend/openapi.json is stale. Regenerate it and the TypeScript types "
        "with `make gen-types` and commit the result."
    )


def test_generated_typescript_exists_and_is_marked_generated() -> None:
    """The generated TS types are committed and clearly marked auto-generated."""
    assert _GENERATED_TS_PATH.is_file(), "Run `make gen-types` to generate frontend/src/api-types.gen.ts."
    header = _GENERATED_TS_PATH.read_text(encoding="utf-8")[:200]
    assert "auto-generated by openapi-typescript" in header


@pytest.fixture(autouse=True)
def _reset_storage_backend() -> Generator[None]:
    set_storage_backend(None)
    yield
    set_storage_backend(None)


@pytest.fixture()
def contract_client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> TestClient:
    """TestClient backed by a cache holding a single representative record."""
    cache_file = tmp_path / "notifications.json"
    cache_file.write_text(
        json.dumps(
            {
                "generated_at": "2024-01-01T00:00:00Z",
                "notifications": [
                    {
                        "account_id": "primary",
                        "account_label": "Primary",
                        "thread_id": "101",
                        "repository": "org/repo-a",
                        "reason": "mention",
                        "subject_title": "Review API changes",
                        "subject_type": "PullRequest",
                        "unread": True,
                        "updated_at": "2024-01-01T00:00:00Z",
                        "score": 90.0,
                        "matched_rules": ["high-score"],
                        "actions_taken": [],
                    }
                ],
            }
        ),
        encoding="utf-8",
    )
    config_file = tmp_path / "corvix.yaml"
    config_file.write_text(
        f"""
github:
  token_env: GITHUB_TOKEN
state:
  cache_file: {cache_file}
dashboards:
  - name: overview
    group_by: repository
    sort_by: score
    include_read: true
""",
        encoding="utf-8",
    )
    monkeypatch.setenv("CORVIX_CONFIG", str(config_file))
    set_storage_backend(JsonFileStorage(path=load_config(config_file).resolve_cache_file()))
    return TestClient(app)


def _assert_conforms(body: bytes, schema: type) -> None:
    """Decode *body* into *schema*, asserting required fields and types match.

    msgspec raises if a required field is missing or mistyped; we additionally
    assert the top-level keys match the schema's fields exactly so the backend
    cannot emit undeclared extras that the OpenAPI contract does not describe.
    """
    decoded = msgspec.json.decode(body, type=schema)
    assert isinstance(decoded, schema)
    expected_keys = {field.name for field in dataclasses.fields(schema)}
    actual_keys = set(json.loads(body))
    assert actual_keys == expected_keys


def test_snapshot_response_conforms_to_schema(contract_client: TestClient) -> None:
    response = contract_client.get("/api/v1/snapshot?dashboard=overview")
    assert response.status_code == 200
    _assert_conforms(response.content, SnapshotResponse)


def test_rule_snippets_response_conforms_to_schema(contract_client: TestClient) -> None:
    response = contract_client.get("/api/v1/notifications/primary/101/rule-snippets?dashboard=overview")
    assert response.status_code == 200
    _assert_conforms(response.content, RuleSnippetsResponse)
